"use strict";

module.exports = [
  {
    files: ["static/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: {
        // Browser
        window: "readonly",
        document: "readonly",
        console: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        FormData: "readonly",
        FileReader: "readonly",
        URL: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        // Loaded from CDN in the page, not bundled
        $: "readonly",
        jQuery: "readonly",
        bootstrap: "readonly",
        // Each page script attaches its own public API to `window.*` (called both from inline
        // HTML `onclick=` handlers and from other page scripts); declared here so ESLint can
        // resolve bare references to them across static/js/*.js.
        activePipeline: "writable",
        adminAddCredits: "writable",
        adminApproveReq: "writable",
        adminRejectReq: "writable",
        adminSetCustomCredit: "writable",
        analyzeStory: "writable",
        approveCarouselItem: "writable",
        approvePipelineAsset: "writable",
        approvePipelineContent: "writable",
        approvePipelineStrategy: "writable",
        approveStrategy: "writable",
        cancelScheduledPostItem: "writable",
        copyStoryOutput: "writable",
        currentCarouselAssets: "writable",
        fetchPlatformPosts: "writable",
        generateContent: "writable",
        generateOpportunitySuggestions: "writable",
        generateStoryFromSelection: "writable",
        lastGeneratedPipeline: "writable",
        lastStrategyData: "writable",
        loadOpportunitySuggestions: "writable",
        loadScheduledPosts: "writable",
        loadStoredPosts: "writable",
        newOpportunityTitles: "writable",
        newlyInsertedPostUrls: "writable",
        openConnectModal: "writable",
        openManualPostModal: "writable",
        openOpportunityModal: "writable",
        openPipelineModal: "writable",
        opportunitySuggestions: "writable",
        pipelineHistory: "writable",
        publishModalPipelineContent: "writable",
        publishPipelineContent: "writable",
        rejectPipelineAsset: "writable",
        rejectPipelineContent: "writable",
        rejectPipelineStrategy: "writable",
        rerunPipelineStrategy: "writable",
        saveAndRerunPipelineStrategy: "writable",
        selectGraphNodeById: "writable",
        showPipelineStageDetail: "writable",
        slideWorkflow: "writable",
        startModalPipelineGeneration: "writable",
        startPipelineGeneration: "writable",
        testLiveAccountConnection: "writable",
        viewHistoryItem: "writable",
        // Optional hook expected to be provided by an admin-only script that isn't always
        // loaded; referenced defensively via `typeof loadAdminPortalData === 'function'`.
        loadAdminPortalData: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none" }],
      "no-undef": "error",
      "no-redeclare": "error",
      "no-var": "warn",
      eqeqeq: ["warn", "smart"],
    },
  },
];
